/**
 * Look up image dimensions from the build-time manifest.
 *
 * The manifest is generated by scripts/generate-image-dims.py which scans
 * every .webp/.jpg/.png under public/images/* and writes
 * content/image-dims.json. At build time we import the JSON directly.
 *
 * Usage:
 *   const { width, height } = imageDims('/images/tours/dongba/banner.webp');
 *   // returns { width: 2400, height: 1350, found: true }
 *   // OR { width: 1920, height: 1080, found: false } (the safe 16:9 fallback)
 *
 * The fallback ensures every image gets width/height attrs (CLS=0 in the
 * common case) even if the manifest is out of sync with public/.
 */
import imageDimsJson from '../../content/image-dims.json';

const FALLBACK = { w: 1920, h: 1080 };

interface DimsMap {
    [url: string]: { w: number; h: number };
}

const dims: DimsMap = imageDimsJson as DimsMap;

export function imageDims(url: string | undefined | null): { width: number; height: number; found: boolean } {
    if (!url) return { width: FALLBACK.w, height: FALLBACK.h, found: false };
    const entry = dims[url];
    if (entry) return { width: entry.w, height: entry.h, found: true };
    return { width: FALLBACK.w, height: FALLBACK.h, found: false };
}

/**
 * Build a srcset string from an image URL by inserting -sm/-md size
 * suffixes before the .webp extension. Returns undefined if the URL
 * doesn't end in .webp (the srcset is silently omitted).
 */
export function srcSetFor(url: string | undefined | null): string | undefined {
    if (!url) return undefined;
    if (!url.toLowerCase().endsWith('.webp')) return undefined;
    return `${url.replace(/\.webp$/, '-sm.webp')} 640w, ${url.replace(/\.webp$/, '-md.webp')} 1024w, ${url} 1920w`;
}